### ISSUE TITLE
Add support to pagination

### ISSUE THREAD

**Issue by fmoliveira** [rpg-maker-repo/rmmv-api#4]

**Comment by deusprogrammer** [comment]
I completed this task.  Please download and test and then close issue.

Also, I will fork the repo and start doing pull requests like you are.

**Comment by deusprogrammer** [comment]
Whoa.  Long time no see XD

**Comment by fmoliveira** [comment]
Heyyy Mike!!

Yeah yeahhh!! How are things going?

**Comment by deusprogrammer** [comment]
Going pretty well!  I've learned so many new things in the last 6 years and most of my work is done purely in Node.js and React.js now.  I've totally moved away from using Java and SQL for anything.  Everything is NoSQL now.  I've been writing a ton of stuff for Twitch.  How about you?  If you care to talk shop, let's chat somewhere other than here.  If you don't remember my email, it's deusprogrammer@gmail.com

**Comment by fmoliveira** [comment]
That's really great news!! Sure, I'm shooting you an email!
